In [5]:
print("OK")

OK


### dataclass decorator
- Used in scenarios to store user-defined data using these data classes
    - Simply to hold data like `configs`, `models` etc
- Can specify constants / make DS immutable i.e frozen = True
- Checking if 2 instances are same.
    - Inherently has __eq__() implemented.

In [6]:
from dataclasses import dataclass

@dataclass
class Product:
    name: str
    price: float
    quantity: int

p1 = Product("iPhone9", 53000, 1)
print( p1.name ) # has __repr__ implemented


@dataclass(frozen=True)
class ProductFrozen:
    name: str
    price: float
    quantity: int

p2 = ProductFrozen("Washing Machine", 60000, 1)
print( p2.name ) # has __repr__ implemented
# p2.name = "Fridge" # Error -> FrozenInstanceError: cannot assign to field 'name'


iPhone9
Washing Machine


In [7]:
import torch


### Lets Look at 2 scenarios
- Low Temperature
- High Temperature

- `Logits` -> `Softmax` -> Apply `Temperature`
- Funda: `Temperature` is always `divided`
    - `Lower` the temperature
        - => we divided by `smaller` number
        - => `gap` b/w low and high prob. `increases`; 
        - => model is `more confident`
    - `Higher` the temperature
        - => we divided by `bigger` number
        - => `gap` b/w low and high prob. `decreases`; 
        - => model is `less confident`

In [16]:
logits = torch.Tensor([-1.9, -3, -2.1])
logits

tensor([-1.9000, -3.0000, -2.1000])

In [17]:
# No Temperature
torch.softmax(logits, dim = -1)

tensor([0.4648, 0.1547, 0.3805])

In [18]:
## Low Temperature
low_temp = 0.4
torch.softmax(logits / low_temp, dim = -1)

tensor([0.5986, 0.0383, 0.3631])

In [19]:
## High Temperature
high_temp = 5
torch.softmax(logits / high_temp, dim = -1)

tensor([0.3619, 0.2904, 0.3477])